language: php
php:
- 7.2
before_script: 
script: echo 'none'
deploy:
  provider: heroku
  app: curso-cefire
  on: master
  skip_cleanup: true
  api_key:
    secure: Rrf2BwVXBWAHsV2qBA5mNBL5pd14WgiARCtqMxuzOk5np8L8ky1EyzJS0WILfYqmzALHtopOf94mk3ITCnKTAc9p6thWngdxneJJTvjo49bamh27RdPMIF5tLjGkbRQXa9RjKqchUO1MXfARlntqCE5OEM1n5h2jpNVS14f5ZUZLg4H6+g9DEMS9YOGFKtllyd//iNE9QOryxHy9g5oy/+mVywly5GwU/LXcYvw/LEIRnNfdZbqbpabv97RMn0+obGpI8CI4nQt0iQigPEN6Cq/YAHlnjx1C7LOuQ86Qutltb0iAhTg9Fzf6SCrGLuen1LAPjFlan3FfUrQ0DWqwqYhafJvRSO5zOecYA6xWi3/4u3E0onFMTSQs3M5hXlOx7p0H67nzdIdS9xPPuD4Fv6uBpfiTLiAM6G5iaenRCrP/ZbRu0m2fVReJzq/sl5MpawB2Osb28jCGVG6PdyBsgsOF0HMN6AdAIHUFtnEOxTr1jtCE48H3ITc7o7HluA2Fe2jRqVJCM1ppAOZvVtLsQ53Bz9iiKHkqrDWiY5OCgwZNJQzmiB2hcy2pNvNwMW1r+ZM7x68NGWuQLvxtiqwmoijV8yxEI/N7J28BjorWyqPbmIzHmJvmpeGzbtMZdacYgcjTX0WbmvpneKRUpICL+vbNQsUjBAeGmRuqoJloag0=
