language: php
php:
- 7.2
before_script: 
script: echo 'none'
deploy:
  provider: heroku
  app: sesion6-travis-heroku
  on: master
  skip_cleanup: true
  api_key:
    secure: azYnthwBWk3tIoQaXRwwZWw9NVAn0cdCURo/SfKI0w9nPrZwM2DyBywXMu+UqHhNHy1OyHuuuykRurlCo9yhmgnSAeB7Lsaxt738F/vnzE2nLzvvWTmT50qeR10QF1rnfxfrhZBP5gniAXXa/gJhO8UVOLoexMP/s1vYVZchBnVwW4kIpcIQpBN/JmInHV9LvdCnodjgxhmNAvJ22zAjujPv4mlYUEKwxSCT0m54cLkE6uFh6xo0fkPRyqSTM5N5VJYQvcf44IuFDsl1e5KSLrV35QDivz/qPgEesHoYD7Hs9av+j+0fifFD/j6KTcRmO1CfSp74ekAnQHx2C17Eh+rLTxYUBrZqZzOgLthSrtJfKRIbqJWNrS65gU8fs7D0d8dDtgulBF0ZCZuEDvZBzQjZFx2w36XKkhPTfOxNLnMHK/+kvExab8SLd0/7vxdgWaE0HeWjPmcpb7Wkvrqdxf8MjjrFBoIUlHUZ6UvDZRbwf87kZ1buGV6UnIk0BHywjQ+/HhwkJRoTEDoN6ewEL2YHLLNFaMNXR0NPEkANpHHwkwhUZrLwbYbNypKO4+eLdD+OWO/CHnugrNyJlH+82Kd3LSXXMWBr2sZOPEq7UTCZhT6BkexKz5zFa42fO58RlWGE1dHM2CjnadVhzQcdMGU853eoU0BfOlqVAHCKIiM=
