language: php
php:
- 7.2
before_script: 
script: echo 'none'
deploy:
  provider: heroku
  app: curso-cefire-github
  on: master
  skip_cleanup: true
  api_key:
    secure: DR/eg4GKe3nIDV3sRhPbNZb7RPP22t7z+i1aq8Gqeqe+CKAmIQLT/wYN6MIDdiib5uorJQ8Gvxr/PXZg4WtBptxmMnfEKeXCFy/yrWCo3HdJeDkUlYXrJN+g/LgffxmnwB4bRm7Pr28xuGiF0SIioOcyA71e97nPcsN/rN+JB8yIA41cGRsKCL0SSEvidEbNMUE8OGlZ1DlusbsIBdC02digQzhgz/V0FvFzVirlBTnffz875dL3ITnO6Q1XHHjoNYxszzmFsLsxnvAb4+9+srdGWZbtIqwNvXHrmLUonl9mY/LiI6yY5SidZbI6l6H1D23E5a+jxVG+3DDu6vWnxAxnTCGUn2F38+9mfZOh/ggudbnwV8weian7kREoyyACKXNHXzJ9ignePXLQqqbUmK0GzNw8/UjjugH8AAKjk2K3gB2vns2BoRXHIYmCXoUf3d9ffzYsbBeFxqb1B54uno7vRy5mblU10zLwqfX31RM+orOrFyIHYx9G6OZSKop78gU66JotlzMw/8zFNlZQ0N5MihuA0q5Sb6SCE2TfUtXA0f6yX0UborlXa00q+dmo+YsPDy115DvKEY+RagsKgCsA4ax6QngwdSixLUuZqMA6wdLLXmFcnjvrAszrZIVjxl/ueIDkspssGF1/icfpfKjmBM9DdxnL4YzPZg4Heps=
